/**
 * This class file was automatically generated by jASN1 (http://www.openmuc.org)
 */

package org.openmuc.asn1.cosem;

import org.openmuc.jasn1.axdr.types.AxdrOctetString;

public class Cosem_Object_Instance_Id extends AxdrOctetString {

	public static final int length = 6;

	public Cosem_Object_Instance_Id() {
		super(length);
	}

	public Cosem_Object_Instance_Id(byte[] octetString) {
		super(length, octetString);
	}

	public Cosem_Object_Instance_Id(String octetString) {
		super(length, AxdrOctetString.getBytesFromString(octetString));
	}

}
