/**
 * This class file was automatically generated by jASN1 (http://www.openmuc.org)
 */

package org.openmuc.asn1.cosem;

import org.openmuc.jasn1.axdr.types.AxdrInteger;

public class Integer16 extends AxdrInteger {

	public Integer16() {
		super(-32768, 32767, -32768);
	}

	public Integer16(byte[] code) {
		super(-32768, 32767, -32768);
		this.code = code;
	}

	public Integer16(long val) {
		super(-32768, 32767, val);
	}

}
