/**
 * This class file was automatically generated by jASN1 (http://www.openmuc.org)
 */

package org.openmuc.asn1.cosem;

import org.openmuc.jasn1.axdr.types.AxdrInteger;

public class Integer32 extends AxdrInteger {

	public Integer32() {
		super(-2147483648, 2147483647, -2147483648);
	}

	public Integer32(byte[] code) {
		super(-2147483648, 2147483647, -2147483648);
		this.code = code;
	}

	public Integer32(long val) {
		super(-2147483648, 2147483647, val);
	}

}
