/**
 * This class file was automatically generated by jASN1 (http://www.openmuc.org)
 */

package org.openmuc.asn1.cosem;

import org.openmuc.jasn1.axdr.types.AxdrInteger;

public class Integer8 extends AxdrInteger {

	public Integer8() {
		super(-128, 127, -128);
	}

	public Integer8(byte[] code) {
		super(-128, 127, -128);
		this.code = code;
	}

	public Integer8(long val) {
		super(-128, 127, val);
	}

}
