/**
 * This class file was automatically generated by jASN1 (http://www.openmuc.org)
 */

package org.openmuc.asn1.cosem;

import org.openmuc.jasn1.axdr.types.AxdrBitString;

public class Invoke_Id_And_Priority extends AxdrBitString {

	public Invoke_Id_And_Priority() {
		super(new byte[1], 8);
	}

}
