/**
 * This class file was automatically generated by jASN1 (http://www.openmuc.org)
 */

package org.openmuc.asn1.cosem;

import org.openmuc.jasn1.axdr.types.AxdrSequenceOf;

public class ReadRequest extends AxdrSequenceOf<Variable_Access_Specification> {

	@Override
	protected Variable_Access_Specification createListElement() {
		return new Variable_Access_Specification();
	}

	protected ReadRequest(int length) {
		super(length);
	}

	public ReadRequest() {
	} // Call empty base constructor

}
