/**
 * This class file was automatically generated by jASN1 (http://www.openmuc.org)
 */

package org.openmuc.asn1.cosem;

import org.openmuc.jasn1.axdr.types.AxdrInteger;

public class Unsigned8 extends AxdrInteger {

	public Unsigned8() {
		super(0, 255, 0);
	}

	public Unsigned8(byte[] code) {
		super(0, 255, 0);
		this.code = code;
	}

	public Unsigned8(long val) {
		super(0, 255, val);
	}

}
