/**
 * This class file was automatically generated by jASN1 (http://www.openmuc.org)
 */

package org.openmuc.asn1.cosem;

import org.openmuc.jasn1.axdr.types.AxdrInteger;

public class Unsigned32 extends AxdrInteger {

	public Unsigned32() {
		super(0, 4294967295L, 0);
	}

	public Unsigned32(byte[] code) {
		super(0, 4294967295L, 0);
		this.code = code;
	}

	public Unsigned32(long val) {
		super(0, 4294967295L, val);
	}

}
